<?php

namespace Filafly\Icons\Phosphor;

use Filafly\Icons\IconSet;
use Filafly\Icons\Phosphor\Enums\Phosphor;
use Filafly\Icons\Phosphor\Enums\PhosphorStyle;

class PhosphorIcons extends IconSet
{
    protected string $pluginId = 'filafly-filament-phosphor-icons';

    protected mixed $iconEnum = Phosphor::class;

    protected mixed $styleEnum = PhosphorStyle::class;

    protected mixed $defaultStyle = PhosphorStyle::Regular;

    protected array $iconMap = [
        'panels::global-search.field' => Phosphor::MagnifyingGlass,
        'panels::pages.dashboard.actions.filter' => Phosphor::Funnel,
        'panels::pages.dashboard.navigation-item' => Phosphor::House,
        'panels::pages.password-reset.request-password-reset.actions.login' => Phosphor::ArrowRight,
        'panels::pages.password-reset.request-password-reset.actions.login.rtl' => Phosphor::ArrowLeft,
        'panels::resources.pages.edit-record.navigation-item' => Phosphor::NotePencil,
        'panels::resources.pages.manage-related-records.navigation-item' => Phosphor::CardsThree,
        'panels::resources.pages.view-record.navigation-item' => Phosphor::Eye,
        'panels::sidebar.collapse-button' => Phosphor::CaretLeft,
        'panels::sidebar.collapse-button.rtl' => Phosphor::CaretRight,
        'panels::sidebar.expand-button' => Phosphor::CaretRight,
        'panels::sidebar.expand-button.rtl' => Phosphor::CaretLeft,
        'panels::sidebar.group.collapse-button' => Phosphor::CaretUp,
        'panels::tenant-menu.billing-button' => Phosphor::CreditCard,
        'panels::tenant-menu.profile-button' => Phosphor::GearSix,
        'panels::tenant-menu.registration-button' => Phosphor::Plus,
        'panels::tenant-menu.toggle-button' => Phosphor::CaretDown,
        'panels::theme-switcher.light-button' => Phosphor::Sun,
        'panels::theme-switcher.dark-button' => Phosphor::Moon,
        'panels::theme-switcher.system-button' => Phosphor::Monitor,
        'panels::topbar.close-sidebar-button' => Phosphor::X,
        'panels::topbar.open-sidebar-button' => Phosphor::List,
        'panels::topbar.group.toggle-button' => Phosphor::CaretDown,
        'panels::topbar.open-database-notifications-button' => Phosphor::Bell,
        'panels::user-menu.profile-item' => Phosphor::UserCircle,
        'panels::user-menu.logout-button' => Phosphor::SignOut,
        'panels::widgets.account.logout-button' => Phosphor::SignOut,
        'panels::widgets.filament-info.open-documentation-button' => Phosphor::BookOpen,
        'panels::widgets.filament-info.open-github-button' => Phosphor::GithubLogo,

        'forms::components.builder.actions.clone' => Phosphor::Copy,
        'forms::components.builder.actions.collapse' => Phosphor::CaretUp,
        'forms::components.builder.actions.delete' => Phosphor::Trash,
        'forms::components.builder.actions.expand' => Phosphor::CaretDown,
        'forms::components.builder.actions.move-down' => Phosphor::ArrowDown,
        'forms::components.builder.actions.move-up' => Phosphor::ArrowUp,
        'forms::components.builder.actions.reorder' => Phosphor::ArrowsDownUp,
        'forms::components.checkbox-list.search-field' => Phosphor::MagnifyingGlass,
        'forms::components.file-upload.editor.actions.drag-crop' => Phosphor::Crop,
        'forms::components.file-upload.editor.actions.drag-move' => Phosphor::ArrowsOutCardinal,
        'forms::components.file-upload.editor.actions.flip-horizontal' => Phosphor::ArrowsInLineHorizontal,
        'forms::components.file-upload.editor.actions.flip-vertical' => Phosphor::ArrowsInLineVertical,
        'forms::components.file-upload.editor.actions.move-down' => Phosphor::ArrowCircleDown,
        'forms::components.file-upload.editor.actions.move-left' => Phosphor::ArrowCircleLeft,
        'forms::components.file-upload.editor.actions.move-right' => Phosphor::ArrowCircleRight,
        'forms::components.file-upload.editor.actions.move-up' => Phosphor::ArrowCircleUp,
        'forms::components.file-upload.editor.actions.rotate-left' => Phosphor::ArrowUDownLeft,
        'forms::components.file-upload.editor.actions.rotate-right' => Phosphor::ArrowUUpRight,
        'forms::components.file-upload.editor.actions.zoom-100' => Phosphor::ArrowsOut,
        'forms::components.file-upload.editor.actions.zoom-in' => Phosphor::MagnifyingGlassPlus,
        'forms::components.file-upload.editor.actions.zoom-out' => Phosphor::MagnifyingGlassMinus,
        'forms::components.key-value.actions.delete' => Phosphor::Trash,
        'forms::components.key-value.actions.reorder' => Phosphor::ArrowsDownUp,
        'forms::components.repeater.actions.clone' => Phosphor::Copy,
        'forms::components.repeater.actions.collapse' => Phosphor::CaretUp,
        'forms::components.repeater.actions.delete' => Phosphor::Trash,
        'forms::components.repeater.actions.expand' => Phosphor::CaretDown,
        'forms::components.repeater.actions.move-down' => Phosphor::ArrowDown,
        'forms::components.repeater.actions.move-up' => Phosphor::ArrowUp,
        'forms::components.repeater.actions.reorder' => Phosphor::ArrowsDownUp,
        'forms::components.select.actions.create-option' => Phosphor::Plus,
        'forms::components.select.actions.edit-option' => Phosphor::NotePencil,
        'forms::components.text-input.actions.hide-password' => Phosphor::EyeSlash,
        'forms::components.text-input.actions.show-password' => Phosphor::Eye,
        'forms::components.toggle-buttons.boolean.false' => Phosphor::X,
        'forms::components.toggle-buttons.boolean.true' => Phosphor::Check,
        'forms::components.wizard.completed-step' => Phosphor::Check,

        'tables::actions.disable-reordering' => Phosphor::Check,
        'tables::actions.enable-reordering' => Phosphor::ArrowsDownUp,
        'tables::actions.filter' => Phosphor::Funnel,
        'tables::actions.group' => Phosphor::CardsThree,
        'tables::actions.open-bulk-actions' => Phosphor::DotsThreeVertical,
        'tables::actions.toggle-columns' => Phosphor::SquareHalf,
        'tables::columns.collapse-button' => Phosphor::CaretDown,
        'tables::columns.icon-column.false' => Phosphor::XCircle,
        'tables::columns.icon-column.true' => Phosphor::CheckCircle,
        'tables::empty-state' => Phosphor::X,
        'tables::filters.query-builder.constraints.boolean' => Phosphor::CheckCircle,
        'tables::filters.query-builder.constraints.date' => Phosphor::Calendar,
        'tables::filters.query-builder.constraints.number' => Phosphor::Sigma,
        'tables::filters.query-builder.constraints.relationship' => Phosphor::ArrowsOut,
        'tables::filters.query-builder.constraints.select' => Phosphor::CaretUpDown,
        'tables::filters.query-builder.constraints.text' => Phosphor::Translate,
        'tables::filters.remove-all-button' => Phosphor::X,
        'tables::grouping.collapse-button' => Phosphor::CaretUp,
        'tables::header-cell.sort-asc-button' => Phosphor::CaretUp,
        'tables::header-cell.sort-button' => Phosphor::CaretDown,
        'tables::header-cell.sort-desc-button' => Phosphor::CaretDown,
        'tables::reorder.handle' => Phosphor::DotsSix,
        'tables::search-field' => Phosphor::MagnifyingGlass,

        'notifications::database.modal.empty-state' => Phosphor::X,
        'notifications::notification.close-button' => Phosphor::X,
        'notifications::notification.danger' => Phosphor::XCircle,
        'notifications::notification.info' => Phosphor::Info,
        'notifications::notification.success' => Phosphor::CheckCircle,
        'notifications::notification.warning' => Phosphor::WarningCircle,

        'actions::action-group' => Phosphor::DotsThreeVertical,
        'actions::create-action.grouped' => Phosphor::Plus,
        'actions::delete-action' => Phosphor::Trash,
        'actions::delete-action.grouped' => Phosphor::Trash,
        'actions::delete-action.modal' => Phosphor::Trash,
        'actions::detach-action' => Phosphor::LinkBreak,
        'actions::detach-action.modal' => Phosphor::LinkBreak,
        'actions::dissociate-action' => Phosphor::LinkBreak,
        'actions::dissociate-action.modal' => Phosphor::LinkBreak,
        'actions::edit-action' => Phosphor::NotePencil,
        'actions::edit-action.grouped' => Phosphor::NotePencil,
        'actions::export-action.grouped' => Phosphor::TrayArrowDown,
        'actions::force-delete-action' => Phosphor::Trash,
        'actions::force-delete-action.grouped' => Phosphor::Trash,
        'actions::force-delete-action.modal' => Phosphor::Trash,
        'actions::import-action.grouped' => Phosphor::TrayArrowUp,
        'actions::modal.confirmation' => Phosphor::Warning,
        'actions::replicate-action' => Phosphor::Copy,
        'actions::replicate-action.grouped' => Phosphor::Copy,
        'actions::restore-action' => Phosphor::ArrowUUpLeft,
        'actions::restore-action.grouped' => Phosphor::ArrowUUpLeft,
        'actions::restore-action.modal' => Phosphor::ArrowUUpLeft,
        'actions::view-action' => Phosphor::Eye,
        'actions::view-action.grouped' => Phosphor::Eye,

        'infolists::components.icon-entry.false' => Phosphor::XCircle,
        'infolists::components.icon-entry.true' => Phosphor::CheckCircle,

        'badge.delete-button' => Phosphor::X,
        'breadcrumbs.separator' => Phosphor::CaretRight,
        'breadcrumbs.separator.rtl' => Phosphor::CaretLeft,
        'modal.close-button' => Phosphor::X,
        'pagination.first-button' => Phosphor::CaretDoubleLeft,
        'pagination.first-button.rtl' => Phosphor::CaretDoubleRight,
        'pagination.last-button' => Phosphor::CaretDoubleRight,
        'pagination.last-button.rtl' => Phosphor::CaretDoubleLeft,
        'pagination.next-button' => Phosphor::CaretRight,
        'pagination.next-button.rtl' => Phosphor::CaretLeft,
        'pagination.previous-button' => Phosphor::CaretLeft,
        'pagination.previous-button.rtl' => Phosphor::CaretRight,
        'section.collapse-button' => Phosphor::CaretDown,
    ];
}
