<?php

namespace Filafly\Icons\Phosphor;

use Filafly\Icons\IconSet;
use Filafly\Icons\Phosphor\Enums\Phosphor;
use Filafly\Icons\Phosphor\Enums\PhosphorStyle;

class PhosphorIcons extends IconSet
{
    protected string $pluginId = 'filafly-filament-phosphor-icons';

    protected mixed $iconEnum = Phosphor::class;

    protected string $iconPrefix = 'phosphor';

    protected mixed $styleEnum = PhosphorStyle::class;

    protected array $iconMap = [
        IconAliases::PANELS_GLOBAL_SEARCH_FIELD => Phosphor::MagnifyingGlass,
        IconAliases::PANELS_PAGES_DASHBOARD_ACTIONS_FILTER => Phosphor::Funnel,
        IconAliases::PANELS_PAGES_DASHBOARD_NAVIGATION_ITEM => Phosphor::House,
        IconAliases::PANELS_PAGES_PASSWORD_RESET_REQUEST_PASSWORD_RESET_ACTIONS_LOGIN => Phosphor::ArrowRight,
        IconAliases::PANELS_PAGES_PASSWORD_RESET_REQUEST_PASSWORD_RESET_ACTIONS_LOGIN_RTL => Phosphor::ArrowLeft,
        IconAliases::PANELS_RESOURCES_PAGES_EDIT_RECORD_NAVIGATION_ITEM => Phosphor::NotePencil,
        IconAliases::PANELS_RESOURCES_PAGES_MANAGE_RELATED_RECORDS_NAVIGATION_ITEM => Phosphor::CardsThree,
        IconAliases::PANELS_RESOURCES_PAGES_VIEW_RECORD_NAVIGATION_ITEM => Phosphor::Eye,
        IconAliases::PANELS_SIDEBAR_COLLAPSE_BUTTON => Phosphor::CaretLeft,
        IconAliases::PANELS_SIDEBAR_COLLAPSE_BUTTON_RTL => Phosphor::CaretRight,
        IconAliases::PANELS_SIDEBAR_EXPAND_BUTTON => Phosphor::CaretRight,
        IconAliases::PANELS_SIDEBAR_EXPAND_BUTTON_RTL => Phosphor::CaretLeft,
        IconAliases::PANELS_SIDEBAR_GROUP_COLLAPSE_BUTTON => Phosphor::CaretUp,
        IconAliases::PANELS_TENANT_MENU_BILLING_BUTTON => Phosphor::CreditCard,
        IconAliases::PANELS_TENANT_MENU_PROFILE_BUTTON => Phosphor::GearSix,
        IconAliases::PANELS_TENANT_MENU_REGISTRATION_BUTTON => Phosphor::Plus,
        IconAliases::PANELS_TENANT_MENU_TOGGLE_BUTTON => Phosphor::CaretDown,
        IconAliases::PANELS_THEME_SWITCHER_LIGHT_BUTTON => Phosphor::Sun,
        IconAliases::PANELS_THEME_SWITCHER_DARK_BUTTON => Phosphor::Moon,
        IconAliases::PANELS_THEME_SWITCHER_SYSTEM_BUTTON => Phosphor::Monitor,
        IconAliases::PANELS_TOPBAR_CLOSE_SIDEBAR_BUTTON => Phosphor::X,
        IconAliases::PANELS_TOPBAR_OPEN_SIDEBAR_BUTTON => Phosphor::List,
        IconAliases::PANELS_TOPBAR_GROUP_TOGGLE_BUTTON => Phosphor::CaretDown,
        IconAliases::PANELS_TOPBAR_OPEN_DATABASE_NOTIFICATIONS_BUTTON => Phosphor::Bell,
        IconAliases::PANELS_USER_MENU_PROFILE_ITEM => Phosphor::UserCircle,
        IconAliases::PANELS_USER_MENU_LOGOUT_BUTTON => Phosphor::SignOut,
        IconAliases::PANELS_WIDGETS_ACCOUNT_LOGOUT_BUTTON => Phosphor::SignOut,
        IconAliases::PANELS_WIDGETS_FILAMENT_INFO_OPEN_DOCUMENTATION_BUTTON => Phosphor::BookOpen,
        IconAliases::PANELS_WIDGETS_FILAMENT_INFO_OPEN_GITHUB_BUTTON => Phosphor::GithubLogo,

        IconAliases::FORMS_COMPONENTS_BUILDER_ACTIONS_CLONE => Phosphor::Copy,
        IconAliases::FORMS_COMPONENTS_BUILDER_ACTIONS_COLLAPSE => Phosphor::CaretUp,
        IconAliases::FORMS_COMPONENTS_BUILDER_ACTIONS_DELETE => Phosphor::Trash,
        IconAliases::FORMS_COMPONENTS_BUILDER_ACTIONS_EXPAND => Phosphor::CaretDown,
        IconAliases::FORMS_COMPONENTS_BUILDER_ACTIONS_MOVE_DOWN => Phosphor::ArrowDown,
        IconAliases::FORMS_COMPONENTS_BUILDER_ACTIONS_MOVE_UP => Phosphor::ArrowUp,
        IconAliases::FORMS_COMPONENTS_BUILDER_ACTIONS_REORDER => Phosphor::ArrowsDownUp,
        IconAliases::FORMS_COMPONENTS_CHECKBOX_LIST_SEARCH_FIELD => Phosphor::MagnifyingGlass,
        IconAliases::FORMS_COMPONENTS_FILE_UPLOAD_EDITOR_ACTIONS_DRAG_CROP => Phosphor::Crop,
        IconAliases::FORMS_COMPONENTS_FILE_UPLOAD_EDITOR_ACTIONS_DRAG_MOVE => Phosphor::ArrowsOutCardinal,
        IconAliases::FORMS_COMPONENTS_FILE_UPLOAD_EDITOR_ACTIONS_FLIP_HORIZONTAL => Phosphor::ArrowsInLineHorizontal,
        IconAliases::FORMS_COMPONENTS_FILE_UPLOAD_EDITOR_ACTIONS_FLIP_VERTICAL => Phosphor::ArrowsInLineVertical,
        IconAliases::FORMS_COMPONENTS_FILE_UPLOAD_EDITOR_ACTIONS_MOVE_DOWN => Phosphor::ArrowCircleDown,
        IconAliases::FORMS_COMPONENTS_FILE_UPLOAD_EDITOR_ACTIONS_MOVE_LEFT => Phosphor::ArrowCircleLeft,
        IconAliases::FORMS_COMPONENTS_FILE_UPLOAD_EDITOR_ACTIONS_MOVE_RIGHT => Phosphor::ArrowCircleRight,
        IconAliases::FORMS_COMPONENTS_FILE_UPLOAD_EDITOR_ACTIONS_MOVE_UP => Phosphor::ArrowCircleUp,
        IconAliases::FORMS_COMPONENTS_FILE_UPLOAD_EDITOR_ACTIONS_ROTATE_LEFT => Phosphor::ArrowUDownLeft,
        IconAliases::FORMS_COMPONENTS_FILE_UPLOAD_EDITOR_ACTIONS_ROTATE_RIGHT => Phosphor::ArrowUUpRight,
        IconAliases::FORMS_COMPONENTS_FILE_UPLOAD_EDITOR_ACTIONS_ZOOM_100 => Phosphor::ArrowsOut,
        IconAliases::FORMS_COMPONENTS_FILE_UPLOAD_EDITOR_ACTIONS_ZOOM_IN => Phosphor::MagnifyingGlassPlus,
        IconAliases::FORMS_COMPONENTS_FILE_UPLOAD_EDITOR_ACTIONS_ZOOM_OUT => Phosphor::MagnifyingGlassMinus,
        IconAliases::FORMS_COMPONENTS_KEY_VALUE_ACTIONS_DELETE => Phosphor::Trash,
        IconAliases::FORMS_COMPONENTS_KEY_VALUE_ACTIONS_REORDER => Phosphor::ArrowsDownUp,
        IconAliases::FORMS_COMPONENTS_REPEATER_ACTIONS_CLONE => Phosphor::Copy,
        IconAliases::FORMS_COMPONENTS_REPEATER_ACTIONS_COLLAPSE => Phosphor::CaretUp,
        IconAliases::FORMS_COMPONENTS_REPEATER_ACTIONS_DELETE => Phosphor::Trash,
        IconAliases::FORMS_COMPONENTS_REPEATER_ACTIONS_EXPAND => Phosphor::CaretDown,
        IconAliases::FORMS_COMPONENTS_REPEATER_ACTIONS_MOVE_DOWN => Phosphor::ArrowDown,
        IconAliases::FORMS_COMPONENTS_REPEATER_ACTIONS_MOVE_UP => Phosphor::ArrowUp,
        IconAliases::FORMS_COMPONENTS_REPEATER_ACTIONS_REORDER => Phosphor::ArrowsDownUp,
        IconAliases::FORMS_COMPONENTS_SELECT_ACTIONS_CREATE_OPTION => Phosphor::Plus,
        IconAliases::FORMS_COMPONENTS_SELECT_ACTIONS_EDIT_OPTION => Phosphor::NotePencil,
        IconAliases::FORMS_COMPONENTS_TEXT_INPUT_ACTIONS_HIDE_PASSWORD => Phosphor::EyeSlash,
        IconAliases::FORMS_COMPONENTS_TEXT_INPUT_ACTIONS_SHOW_PASSWORD => Phosphor::Eye,
        IconAliases::FORMS_COMPONENTS_TOGGLE_BUTTONS_BOOLEAN_FALSE => Phosphor::X,
        IconAliases::FORMS_COMPONENTS_TOGGLE_BUTTONS_BOOLEAN_TRUE => Phosphor::Check,
        IconAliases::FORMS_COMPONENTS_WIZARD_COMPLETED_STEP => Phosphor::Check,

        IconAliases::TABLES_ACTIONS_DISABLE_REORDERING => Phosphor::Check,
        IconAliases::TABLES_ACTIONS_ENABLE_REORDERING => Phosphor::ArrowsDownUp,
        IconAliases::TABLES_ACTIONS_FILTER => Phosphor::Funnel,
        IconAliases::TABLES_ACTIONS_GROUP => Phosphor::CardsThree,
        IconAliases::TABLES_ACTIONS_OPEN_BULK_ACTIONS => Phosphor::DotsThreeVertical,
        IconAliases::TABLES_ACTIONS_TOGGLE_COLUMNS => Phosphor::SquareHalf,
        IconAliases::TABLES_COLUMNS_COLLAPSE_BUTTON => Phosphor::CaretDown,
        IconAliases::TABLES_COLUMNS_ICON_COLUMN_FALSE => Phosphor::XCircle,
        IconAliases::TABLES_COLUMNS_ICON_COLUMN_TRUE => Phosphor::CheckCircle,
        IconAliases::TABLES_EMPTY_STATE => Phosphor::X,
        IconAliases::TABLES_FILTERS_QUERY_BUILDER_CONSTRAINTS_BOOLEAN => Phosphor::CheckCircle,
        IconAliases::TABLES_FILTERS_QUERY_BUILDER_CONSTRAINTS_DATE => Phosphor::Calendar,
        IconAliases::TABLES_FILTERS_QUERY_BUILDER_CONSTRAINTS_NUMBER => Phosphor::Sigma,
        IconAliases::TABLES_FILTERS_QUERY_BUILDER_CONSTRAINTS_RELATIONSHIP => Phosphor::ArrowsOut,
        IconAliases::TABLES_FILTERS_QUERY_BUILDER_CONSTRAINTS_SELECT => Phosphor::CaretUpDown,
        IconAliases::TABLES_FILTERS_QUERY_BUILDER_CONSTRAINTS_TEXT => Phosphor::Translate,
        IconAliases::TABLES_FILTERS_REMOVE_ALL_BUTTON => Phosphor::X,
        IconAliases::TABLES_GROUPING_COLLAPSE_BUTTON => Phosphor::CaretUp,
        IconAliases::TABLES_HEADER_CELL_SORT_ASC_BUTTON => Phosphor::CaretUp,
        IconAliases::TABLES_HEADER_CELL_SORT_BUTTON => Phosphor::CaretDown,
        IconAliases::TABLES_HEADER_CELL_SORT_DESC_BUTTON => Phosphor::CaretDown,
        IconAliases::TABLES_REORDER_HANDLE => Phosphor::DotsSix,
        IconAliases::TABLES_SEARCH_FIELD => Phosphor::MagnifyingGlass,

        IconAliases::NOTIFICATIONS_DATABASE_MODAL_EMPTY_STATE => Phosphor::X,
        IconAliases::NOTIFICATIONS_NOTIFICATION_CLOSE_BUTTON => Phosphor::X,
        IconAliases::NOTIFICATIONS_NOTIFICATION_DANGER => Phosphor::XCircle,
        IconAliases::NOTIFICATIONS_NOTIFICATION_INFO => Phosphor::Info,
        IconAliases::NOTIFICATIONS_NOTIFICATION_SUCCESS => Phosphor::CheckCircle,
        IconAliases::NOTIFICATIONS_NOTIFICATION_WARNING => Phosphor::WarningCircle,

        IconAliases::ACTIONS_ACTION_GROUP => Phosphor::DotsThreeVertical,
        IconAliases::ACTIONS_CREATE_ACTION_GROUPED => Phosphor::Plus,
        IconAliases::ACTIONS_DELETE_ACTION => Phosphor::Trash,
        IconAliases::ACTIONS_DELETE_ACTION_GROUPED => Phosphor::Trash,
        IconAliases::ACTIONS_DELETE_ACTION_MODAL => Phosphor::Trash,
        IconAliases::ACTIONS_DETACH_ACTION => Phosphor::LinkBreak,
        IconAliases::ACTIONS_DETACH_ACTION_MODAL => Phosphor::LinkBreak,
        IconAliases::ACTIONS_DISSOCIATE_ACTION => Phosphor::LinkBreak,
        IconAliases::ACTIONS_DISSOCIATE_ACTION_MODAL => Phosphor::LinkBreak,
        IconAliases::ACTIONS_EDIT_ACTION => Phosphor::NotePencil,
        IconAliases::ACTIONS_EDIT_ACTION_GROUPED => Phosphor::NotePencil,
        IconAliases::ACTIONS_EXPORT_ACTION_GROUPED => Phosphor::TrayArrowDown,
        IconAliases::ACTIONS_FORCE_DELETE_ACTION => Phosphor::Trash,
        IconAliases::ACTIONS_FORCE_DELETE_ACTION_GROUPED => Phosphor::Trash,
        IconAliases::ACTIONS_FORCE_DELETE_ACTION_MODAL => Phosphor::Trash,
        IconAliases::ACTIONS_IMPORT_ACTION_GROUPED => Phosphor::TrayArrowUp,
        IconAliases::ACTIONS_MODAL_CONFIRMATION => Phosphor::Warning,
        IconAliases::ACTIONS_REPLICATE_ACTION => Phosphor::Copy,
        IconAliases::ACTIONS_REPLICATE_ACTION_GROUPED => Phosphor::Copy,
        IconAliases::ACTIONS_RESTORE_ACTION => Phosphor::ArrowUUpLeft,
        IconAliases::ACTIONS_RESTORE_ACTION_GROUPED => Phosphor::ArrowUUpLeft,
        IconAliases::ACTIONS_RESTORE_ACTION_MODAL => Phosphor::ArrowUUpLeft,
        IconAliases::ACTIONS_VIEW_ACTION => Phosphor::Eye,
        IconAliases::ACTIONS_VIEW_ACTION_GROUPED => Phosphor::Eye,

        IconAliases::INFOLISTS_COMPONENTS_ICON_ENTRY_FALSE => Phosphor::XCircle,
        IconAliases::INFOLISTS_COMPONENTS_ICON_ENTRY_TRUE => Phosphor::CheckCircle,

        IconAliases::BADGE_DELETE_BUTTON => Phosphor::X,
        IconAliases::BREADCRUMBS_SEPARATOR => Phosphor::CaretRight,
        IconAliases::BREADCRUMBS_SEPARATOR_RTL => Phosphor::CaretLeft,
        IconAliases::MODAL_CLOSE_BUTTON => Phosphor::X,
        IconAliases::PAGINATION_FIRST_BUTTON => Phosphor::CaretDoubleLeft,
        IconAliases::PAGINATION_FIRST_BUTTON_RTL => Phosphor::CaretDoubleRight,
        IconAliases::PAGINATION_LAST_BUTTON => Phosphor::CaretDoubleRight,
        IconAliases::PAGINATION_LAST_BUTTON_RTL => Phosphor::CaretDoubleLeft,
        IconAliases::PAGINATION_NEXT_BUTTON => Phosphor::CaretRight,
        IconAliases::PAGINATION_NEXT_BUTTON_RTL => Phosphor::CaretLeft,
        IconAliases::PAGINATION_PREVIOUS_BUTTON => Phosphor::CaretLeft,
        IconAliases::PAGINATION_PREVIOUS_BUTTON_RTL => Phosphor::CaretRight,
        IconAliases::SECTION_COLLAPSE_BUTTON => Phosphor::CaretDown,
    ];
}
